routes:
  /:
    template: home

  /about/:
    template: about

collections:
  /posts/:
    permalink: /p/{slug}/
    template: posts
    filter: tag:hash-posts

  /notes/:
    permalink: /notes/{slug}/
    template: notes
    filter: tag:hash-notes

  /essays/:
    permalink: /essays/{slug}/
    template: essays
    filter: tag:hash-essays

  /diary/:
    permalink: /diary/{slug}/
    template: diary
    filter: tag:hash-diary

taxonomies:
  tag: /tags/{slug}/
  author: /author/{slug}/
